# Generated by Django 6.0.5 on 2026-05-18 14:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la dimension')),
                ('icon', models.CharField(default='fas fa-user', help_text='Ex : fas fa-graduation-cap', max_length=60, verbose_name='Icône FontAwesome')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dimension biographique',
                'verbose_name_plural': 'Portrait — Double dimension',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name="Texte de l'engagement")),
                ('icon', models.CharField(default='fas fa-check', max_length=60, verbose_name='Icône FontAwesome')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Engagement',
                'verbose_name_plural': 'Engagements',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComparativeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('intro', models.TextField(verbose_name='Introduction')),
                ('promise_column_title', models.CharField(default="La Promesse — L'inexpérience", max_length=100, verbose_name='Titre colonne Promesse')),
                ('reality_column_title', models.CharField(default='Le Vécu — La réalité', max_length=100, verbose_name='Titre colonne Réalité')),
                ('conclusion', models.TextField(verbose_name='Conclusion')),
                ('cover_image', models.ImageField(blank=True, upload_to='analyses/', verbose_name='Image de couverture')),
                ('published_at', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié ?')),
            ],
            options={
                'verbose_name': 'Analyse comparative',
                'verbose_name_plural': 'Analyse comparative — Doumbouya',
            },
        ),
        migrations.CreateModel(
            name='KeyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Valeur affichée')),
                ('numeric_value', models.IntegerField(blank=True, help_text="Entier pour l'animation compteur. Laisser vide pour désactiver.", null=True, verbose_name='Valeur numérique (animation)')),
                ('suffix', models.CharField(blank=True, help_text='Ex : +, ans, publications', max_length=20, verbose_name='Suffixe')),
                ('start_value', models.IntegerField(default=0, verbose_name='Valeur de départ')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('icon', models.CharField(default='fas fa-star', max_length=60, verbose_name='Icône FontAwesome')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Chiffre clé',
                'verbose_name_plural': 'Chiffres clés',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='news/covers/', verbose_name='Image de couverture')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('published_at', models.DateField(default=datetime.date.today, verbose_name='Date de publication')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié ?')),
            ],
            options={
                'verbose_name': 'Actualité de campagne',
                'verbose_name_plural': 'Actualités de campagne',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'axe")),
                ('icon', models.CharField(default='fas fa-check-circle', max_length=60, verbose_name='Icône FontAwesome')),
                ('description', models.TextField(verbose_name='Description')),
                ('points', models.TextField(blank=True, help_text='Un point par ligne.', verbose_name='Points du programme')),
                ('is_featured', models.BooleanField(default=False, help_text='Affichage pleine largeur en tête de grille.', verbose_name='Axe vedette ?')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Axe du programme',
                'verbose_name_plural': 'Programme — Axes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('category', models.CharField(choices=[('academic', 'Article académique'), ('report', 'Rapport / Étude'), ('opinion', 'Tribune / Opinion'), ('comparative', 'Étude comparative')], max_length=30, verbose_name='Catégorie')),
                ('year', models.CharField(max_length=10, verbose_name='Année')),
                ('institution', models.CharField(blank=True, help_text='Ex : Université Cheikh Anta Diop', max_length=200, verbose_name='Institution')),
                ('summary', models.TextField(verbose_name='Résumé')),
                ('cover_image', models.ImageField(blank=True, upload_to='publications/covers/', verbose_name='Image de couverture')),
                ('pdf_url', models.URLField(blank=True, help_text='URL externe ou Supabase Storage', verbose_name='Lien PDF')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant ?')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publication académique',
                'verbose_name_plural': 'Publications & Travaux académiques',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(default='Abdourahamane Adra Diallo', max_length=200, verbose_name='Nom du candidat')),
                ('slogan', models.CharField(default='La connaissance au service de la Guinée', max_length=300, verbose_name='Slogan')),
                ('bio_short', models.TextField(default='Juriste, politologue, chercheur — une expertise académique au service de la Guinée.', verbose_name='Accroche hero (bio courte)')),
                ('candidate_photo', models.ImageField(blank=True, help_text='Portrait vertical recommandé (3:4). Remplace le cercle AD dans le hero.', null=True, upload_to='candidate/', verbose_name='Photo du candidat')),
                ('party_name', models.CharField(default='FRONDEG', max_length=100, verbose_name='Nom du parti')),
                ('election_date', models.DateField(default=datetime.date(2026, 5, 24), verbose_name="Date de l'élection")),
                ('meta_description', models.TextField(blank=True, default='Adra Diallo, juriste et politologue, candidat FRONDEG sur la liste nationale aux élections législatives guinéennes du 24 mai 2026.', verbose_name='Description méta (SEO)')),
                ('hero_tag', models.CharField(default='FRONDEG · Liste Nationale 2026', max_length=100, verbose_name='Bandeau tag')),
                ('hero_title_line1', models.CharField(default='La Guinée', max_length=100, verbose_name='Titre — ligne 1')),
                ('hero_title_line2', models.CharField(default='mérite', max_length=100, verbose_name='Titre — ligne 2')),
                ('hero_title_accent', models.CharField(default="l'excellence.", help_text="Affiché en couleur d'accent — le mot-clé fort du slogan.", max_length=100, verbose_name='Titre — ligne 3 (accent)')),
                ('hero_candidate_name', models.CharField(default='Abdourahamane « Adra » Diallo', max_length=200, verbose_name='Nom du candidat (hero)')),
                ('hero_role', models.CharField(default='Juriste · Politologue · Candidat FRONDEG', max_length=300, verbose_name='Rôle / titre (sous le nom)')),
                ('hero_desc_before', models.CharField(blank=True, default='Chercheur au CDPIAC depuis 2015, ', max_length=300, verbose_name='Description — texte avant le gras')),
                ('hero_desc_strong', models.CharField(blank=True, default='expert en gouvernance et conflits africains', max_length=150, verbose_name='Description — texte en gras')),
                ('hero_desc_after', models.CharField(blank=True, default=", Adra Diallo porte une vision ancrée dans la science et l'engagement citoyen. Il se présente devant vous avec la rigueur du chercheur et la chaleur de l'homme de terrain.", max_length=500, verbose_name='Description — texte après le gras')),
                ('hero_btn_primary', models.CharField(default='Découvrir le programme', max_length=100, verbose_name='Bouton principal')),
                ('hero_btn_secondary', models.CharField(default='Mon parcours', max_length=100, verbose_name='Bouton secondaire')),
                ('hero_placeholder_initials', models.CharField(default='AD', max_length=5, verbose_name='Initiales (cercle placeholder)')),
                ('hero_placeholder_name', models.CharField(default='Adra Diallo', max_length=200, verbose_name='Nom (panneau droit)')),
                ('hero_placeholder_role', models.CharField(default='Juriste · Politologue · Chercheur', max_length=200, verbose_name='Rôle (panneau droit)')),
                ('hero_banner_label1', models.CharField(default='Élections législatives', max_length=100, verbose_name='Bandeau — libellé 1')),
                ('hero_banner_date', models.CharField(default='24 mai 2026', max_length=50, verbose_name='Bandeau — date')),
                ('hero_banner_label2', models.CharField(default='Liste nationale', max_length=100, verbose_name='Bandeau — libellé 2')),
                ('hero_banner_label3', models.CharField(default='FRONDEG', max_length=100, verbose_name='Bandeau — libellé 3')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='TimelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30, verbose_name='Année / période')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='fas fa-circle', max_length=60, verbose_name='Icône FontAwesome')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Étape du parcours',
                'verbose_name_plural': 'Parcours — Étapes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Thème')),
                ('promise_text', models.TextField(verbose_name='Texte — Promesse')),
                ('reality_text', models.TextField(verbose_name='Texte — Réalité')),
                ('order', models.PositiveIntegerField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='campaign.comparativeanalysis')),
            ],
            options={
                'verbose_name': 'Point de comparaison',
                'verbose_name_plural': 'Points de comparaison',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo défilante du hero (format portrait 3:4 recommandé).', upload_to='candidate/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende (optionnelle)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='campaign.sitesettings')),
            ],
            options={
                'verbose_name': 'Photo du carousel hero',
                'verbose_name_plural': 'Carousel hero — Photos',
                'ordering': ['order'],
            },
        ),
    ]
