# Generated by Django 6.0.5 on 2026-05-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('message', models.TextField(verbose_name='Message')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu ?')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages reçus',
                'ordering': ['-received_at'],
            },
        ),
    ]
